spring:
  application:
    name: miniDoorayTaskAPI
  datasource:
    url: jdbc:mysql://220.67.216.14:13306/nhn_academy_8?serverTimezone=Asia/Seoul
    username: nhn_academy_8
    password: zq#ueLhsLMT258C?
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate ??
  jpa:
    hibernate:
      # ddl-auto: Spring Boot? ??? ? ?????? ???? ??? ???? ??
      # update: ??? ?? ??? DB? ?? (?? ???? ?? ?? ??)
      # none: ???? ? ? (?? ?? ??)
      ddl-auto: none
    show-sql: true # ???? SQL ??? ??? ?? (?? ? ??)
    properties:
      hibernate:
        format_sql: true # SQL ??? ?? ?? ??
